### ISSUE TITLE
Unable to interpret/ Not getting expect results.

### ISSUE THREAD

**Issue by Gopal-Dahale** [vdasu/lighter-r#1]
### Steps to reproduce the problem

Run the following commands in terminal
1. `git clone https://github.com/vdasu/lighter-r.git`
2. `cd lighter-r`
3. `make`
4. `./non-lin-search -qv -i "0123 4567 89ab cdef" -o "c690 1a2b 385d 4e7f" -p 2`

### What is the current behaviour?

The output does not give enough information about the construction of the SBox circuit. I get the following output for SKINNY SBox.

```
Thread number: 2

From : 0123 4567 89AB CDEF 
To   : C690 1A2B 385D 4E7F 
0
100
200
300
400
500
600
700
800
900
1000
1100
1200

f1_succ : 0 (1) 
Total = 1
f2_succ : 0 (1) 
Total = 1
```

Also, no new files are generated which contain the SBox. Either I am not able to follow the output (If something's missing from my side, please correct me) or there is something else wrong. 

### What is the expected behaviour?

The output should describe a sequence of operations on 4 qubits.

### Screenshots (optional but very helpful)
![image](https://user-images.githubusercontent.com/49199003/168441497-90fe8fda-258a-4025-aa50-a9911deabe87.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: Ubuntu 22.04 LTS
 - GNU Make 4.3

**Comment by vdasu** [comment]
Hello Gopal, to generate the implementation of the circuit you need to pass the logic library using the `-f` argument. Additionally, if you want to generate the implementation of the SKINNY S-Box, your start function `-i` needs to be the identity permutation which is `00FF0F0F33335555`. LIGHTER-R assumes this as the default and you do not need to explicitly pass this as an argument. So the command to generate an implementation of the SKINYY S-Box will look like:

`./non-lin-search -qv -o "C6901A2B385D4E7F" -f "libraries/MCT_gc.conf" `

After this executes, you should see one or more files that look like: `implementation_C6901A2B385D4E7F_*.c`. These files contain the implementation of the S-Box.

**Comment by Gopal-Dahale** [comment]
You said that the `-i` needs to be an identity permutation. Is it only the case for SKINNY SBox or in general, does this have to be true for any SBox that I want to generate?

**Comment by Gopal-Dahale** [comment]
Although I am getting a result, does this behaviour expected?

```
sh: 1: notify-send: not found
```
![image](https://user-images.githubusercontent.com/49199003/168470148-3ef5197d-1770-4a64-91f9-7f7c0562079e.png)

**Comment by vdasu** [comment]
> You said that the `-i` needs to be an identity permutation. Is it only the case for SKINNY SBox or in general, does this have to be true for any SBox that I want to generate?

Yes, this is in general.

**Comment by vdasu** [comment]
> Although I am getting a result, does this behaviour expected?
> 
> ```
> sh: 1: notify-send: not found
> ```
> 
> ![image](https://user-images.githubusercontent.com/49199003/168470148-3ef5197d-1770-4a64-91f9-7f7c0562079e.png)

You can ignore that. I think it's because you are running it on Colab.

**Comment by Gopal-Dahale** [comment]
Ok, thank you for the help @vdasu. It's nice that you actively helped me. I will close this issue now. This might help someone in future. Thank you.

**Comment by wodaka** [comment]
Very helpful!
